name: Rust
on:
  [workflow_dispatch, push, pull_request]

jobs:
  sanitary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt clippy

      - name: Template fake
        run: |
          cargo verify-project --quiet || cargo init --name fake --bin -- $PWD

      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets
